from enum import Enum


class EmployedType(Enum):
    AGRICULTURE = "AGRICULTURE"
    MINING = "MINING"
    UTILITIES = "UTILITIES"
    CONSTRUCTION = "CONSTRUCTION"
    MANUFACTURING = "MANUFACTURING"
    WHOLESALE = "WHOLESALE"
    RETAIL = "RETAIL"
    TRANSPORT = "TRANSPORT"
    INFORMATION = "INFORMATION"
    FINANCE = "FINANCE"
    REAL_ESTATE = "REAL_ESTATE"
    PROFESSIONAL = "PROFESSIONAL"
    MANAGEMENT = "MANAGEMENT"
    EDUCATION = "EDUCATION"
    HEALTH = "HEALTH"
    ART = "ART"
    FOOD = "FOOD"
    PUBLIC = "PUBLIC"
    WASTE = "WASTE"
