from enum import Enum


class KycStatus(Enum):
    KYC_NOT_READY = "KYC_NOT_READY"
    KYC_READY = "KYC_READY"
    KYC_PROCESSING = "KYC_PROCESSING"
    KYC_APPROVED = "KYC_APPROVED"
    KYC_INFO_REQUIRED = "KYC_INFO_REQUIRED"
    KYC_DOC_REQUIRED = "KYC_DOC_REQUIRED"
    KYC_MANUAL_REVIEW = "KYC_MANUAL_REVIEW"
    KYC_DENIED = "KYC_DENIED"
