CREATE TABLE SIGAME_TIME_EXPERIENCE (
	CODE varchar(3) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SIGAME_TIME_EXPERIENCE (CODE, DESCRIPTION) VALUES ('NONE', 'N/D');
INSERT INTO SIGAME_TIME_EXPERIENCE (CODE, DESCRIPTION) VALUES ('YRS_1_2', '1 a 2 anos');
INSERT INTO SIGAME_TIME_EXPERIENCE (CODE, DESCRIPTION) VALUES ('YRS_3_5', '3 a 5 anos');
INSERT INTO SIGAME_TIME_EXPERIENCE (CODE, DESCRIPTION) VALUES ('YRS_5_10', '5 a 10 anos');
INSERT INTO SIGAME_TIME_EXPERIENCE (CODE, DESCRIPTION) VALUES ('YRS_10_', 'Mais de 10 anos');
COMMIT





