CREATE TABLE SIGAME_GENDER (
	CODE varchar(3) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SIGAME_GENDER (CODE, DESCRIPTION) VALUES ('M', 'MASCULINO');
INSERT INTO SIGAME_GENDER (CODE, DESCRIPTION) VALUES ('F', 'Feminino');
INSERT INTO SIGAME_GENDER (CODE, DESCRIPTION) VALUES ('O', 'OUTRO');
INSERT INTO SIGAME_GENDER (CODE, DESCRIPTION) VALUES ('NI', 'NÃO DESEJO INFORMAR');
COMMIT