CREATE TABLE SINCAD_EXTERNAL_ISSUER (
	CODE varchar(10) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'SSP', 'Secretaria De Seguranca Publica');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'IFP', 'Instituto Felix Pacheco');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRA', 'Conselho Regional De Administração');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CREA', 'Cons. Reg. De Engenharia E Arquitetura');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'OAB', 'Ordem Dos Advogados Do Brasil');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRM', 'Conselho Regional De Medicina');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRO', 'Conselho Regional De Odontologia');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MAER', 'Ministério Da Aeronáutica');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRE', 'Conselho Regional De Economia');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MEX', 'Ministério Do Exército');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRC', 'Conselho Regional De Contabilidade');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CREF', 'Cons. Reg.  Fisioterapia E Terap. Ocupa');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MJ', 'Ministério Da Justiça');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MRE', 'Min. Rel. Exterior');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRCI', 'Conselho Reg. Corretores De Imóveis');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRF', 'Conselho Regional De Farmacia');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CRP', 'Conselho Regional De Psicologia');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'INI', 'Instituto Nacional De Identificacao');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MG', 'Ministerio Da Guerra');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'MTPS', 'Minist Do Trabalho E Previdencia Social');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'PM', 'Policia Militar');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'PMES', 'Pol. Militar Do Es');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CTPS', 'Carteira De Trabalho E Previdencia Soci');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'IPF', 'Instituto Pereira Faustino');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'SPTC', 'Secretaria De Policia Tecnica Civil');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CBM', 'Corpo De Bombeiros Militar');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'AGU', 'Advocacia Geral Da União');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'SPC', 'Superintendencia De Policia Civil');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CC', 'Cartório De Registro Civil');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'IITP', 'Instituto De Identificacao E Tecnica Po');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'DIC', 'Departamento De Identificacao Civil');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CNH', 'Carteira Nacional De Transito');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'CNT', 'Conselho Nacional De Transito');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'TTS', 'Teste');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'INVALIDO', 'Invalido');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'DETRAN', 'Departamento De Trânsito');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'TRE', 'Tribunal Regional Eleitoral');
INSERT INTO SINCAD_EXTERNAL_ISSUER (CODE, DESCRIPTION) VALUES ( 'DPF', 'Polícia Federal');
COMMIT