CREATE TABLE SINCAD_EXTERNAL_EMPLOY_TYPES (
	CODE varchar(25) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('AGRICULTURE', 'AGRICULTURE');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('MINING', 'MINING');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('UTILITIES', 'UTILITIES');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('CONSTRUCTION', 'CONSTRUCTION');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('MANUFACTURING', 'MANUFACTURING');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('WHOLESALE', 'WHOLESALE');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('RETAIL', 'RETAIL');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('TRANSPORT', 'TRANSPORT');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('INFORMATION', 'INFORMATION');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('FINANCE', 'FINANCE');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('REAL_ESTATE', 'REAL_ESTATE');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('PROFESSIONAL', 'PROFESSIONAL');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('MANAGEMENT', 'MANAGEMENT');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('EDUCATION', 'EDUCATION');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('HEALTH', 'HEALTH');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('ART', 'ART');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('FOOD', 'FOOD');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('PUBLIC', 'PUBLIC');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_TYPES (CODE, DESCRIPTION) VALUES ('WASTE', 'WASTE');
COMMIT