CREATE TABLE SINCAD_EXTERNAL_EMPLOY_STATUS (
	CODE varchar(25) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);


INSERT INTO SINCAD_EXTERNAL_EMPLOY_STATUS (CODE, DESCRIPTION) VALUES ('EMPLOYED', 'EMPREGADO(A)');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_STATUS (CODE, DESCRIPTION) VALUES ('RETIRED', 'APOSENTADO(A)');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_STATUS (CODE, DESCRIPTION) VALUES ('STUDENT', 'ALUNO(A)');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_STATUS (CODE, DESCRIPTION) VALUES ('UNEMPLOYED', 'DESEMPREGADO(A)');
INSERT INTO SINCAD_EXTERNAL_EMPLOY_STATUS (CODE, DESCRIPTION) VALUES ('SELF_EMPLOYED', 'TRABALHADOR(A) POR CONTA PRÓPRIA');
COMMIT