CREATE TABLE SINCAD_EXTERNAL_NATIONALITY (
	CODE numeric(10) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SINCAD_EXTERNAL_NATIONALITY (CODE, DESCRIPTION) VALUES (1, 'BRASILEIRO NATO');
INSERT INTO SINCAD_EXTERNAL_NATIONALITY (CODE, DESCRIPTION) VALUES (2, 'BRASILEIRO NATURALIZADO');
INSERT INTO SINCAD_EXTERNAL_NATIONALITY (CODE, DESCRIPTION) VALUES (3, 'ESTRANGEIRO');
COMMIT
