CREATE TABLE SINCAD_EXTERNAL_MARITAL_STATUS (
	CODE numeric(10) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	PRIMARY KEY (CODE)
);

INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (1, 'SOLTEIRO(A) ');
INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (2, 'CASADO(A)');
INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (3, 'SEPARADO(A) JUDICIALMENTE');
INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (4, 'DIVORCIADO(A) ');
INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (5, 'VIÚVO(A) ');
INSERT INTO SINCAD_EXTERNAL_MARITAL_STATUS (CODE, DESCRIPTION) VALUES (6, 'UNIÃO ESTÁVEL');
COMMIT