CREATE TABLE SINCAD_EXTERNAL_IDENTIFICATION_TYPE (
	CODE varchar(10) NOT NULL,
	DESCRIPTION varchar(255) NOT NULL,
	COUNTRY varchar(50),
	PRIMARY KEY (CODE)
);

INSERT INTO SINCAD_EXTERNAL_IDENTIFICATION_TYPE (CODE, DESCRIPTION, COUNTRY) VALUES ('CH', 'CARTEIRA NACIONAL DE HABILITACAO', 'BRASIL');
INSERT INTO SINCAD_EXTERNAL_IDENTIFICATION_TYPE (CODE, DESCRIPTION, COUNTRY) VALUES ('RG', 'REGISTRO GERAL', 'BRASIL');
COMMIT
